#!/usr/bin/env bash

# Made By Randomguy (https://github.com/Randomguy-8)
# Last Modified On Sat 13 Aug 2022 02:36:55 PM IST

## Todo
# Add other funtion
# Make OutputFile and export some predefine functions in it

source config.sh

# Predefines
Version="22.8.13"
Usage='usage: pagebarsig [Options] <value>\n  Where Optons are:
  -incb, -decb\t:Increase or Decrease Brightness
  -incv, -decv\t:Increase or Decrease Volume\n  -togv\t\t:Toggle Volume on or off
  -incn, -decn\t:Increase or Decrease Night-light temperature\n  -togn\t\t:Toggle Night-line on or off
  -showf\t:Show Full clock on Statusbar'


StartupCheck_(){
	[[ ! -f "$OutputFile" ]] && mkdir -p "${OutputFile%/*}" && touch "$OutputFile"
	[[ ! -e "$TmpFile/redshift-temp" ]] && mkdir -p "/tmp/pagebar" && touch "$TmpFile/redshift-temp"
	[[ -z "$1" ]] && echo -e "$Usage" >&2 && exit 64
}


StartupCheck_ "$1" "$2"
case $1 in
	'-incb')
		echo "Brig++ $2" >>$OutputFile
		xbacklight -inc "$2" 2>&1>>"$OutputFile"
		;;
	'-decb')
		echo "Brig-- $2" >>"$OutputFile"
		xbacklight -dec "$2" 2>&1>>"$OutputFile"
		;;
	'-incv')
		echo "Vol++ $2" >>"$OutputFile"
		amixer set Master 2%+
		;;
	'-decv')
		echo "Vol-- $2" >>"$OutputFile"
		amixer set Master 2%-
		;;
	'-togv')
		Status=$(amixer sget Master | tail -n1 | sed -r "s/.*\[(.*)\]/\1/")

		if [[ $Status == "on" ]]; then
			echo "Vol off" >>"$OutputFile"
			amixer set Master mute | tail -n1 2>&1>>"$OutputFile"
		else
			echo "Vol on" >>"$OutputFile"
			amixer set Master unmute | tail -n1 2>&1>>"$OutputFile"
		fi
		;;
	'-incn')
		StartTemp=$2
		[[ -z $StartTemp && -z $(cat "$TmpFile/redshift-temp") ]] && StartTemp=1000 || StartTemp="$(( $(cat "$TmpFile/redshift-temp")+$NLightJump ))"
		[[ $StartTemp -gt 4500 ]] && StartTemp=4500
		echo $StartTemp >"$TmpFile/redshift-temp"

		echo $StartTemp
		redshift -P -O $StartTemp
		;;
	'-decn')
		StartTemp=$2
		[[ -z $StartTemp && -z $(cat "$TmpFile/redshift-temp") ]] && StartTemp=1000 || StartTemp="$(( $(cat "$TmpFile/redshift-temp")-$NLightJump ))"
		[[ $StartTemp -lt 1000 ]] && StartTemp=1000
		echo $StartTemp >"$TmpFile/redshift-temp"

		echo $StartTemp
		redshift -P -O $StartTemp
		;;
	'-togn')
		redshift -x
		;;
	'-togw')
		[[ ! -z $(ps -e | grep wpa_supplicant) ]] && echo $Password | sudo -S pkill "wpa_supplicant" && echo "Turned off network Interface" 1>>$OutputFile && exit 64
		echo $Password | sudo -S wpa_supplicant -B -i$Interface -c $WpaConfigFile 2>&1>>$OutputFile
		;;
	'-showfc')
		echo "1" >"$TmpFile/Connect"
		;;
	'-showde')
		echo "0" >"$TmpFile/Connect"
		;;
	'-showcp')
		echo "2" >"$TmpFile/Connect"
		;;
	'-showwi')
		echo "3" >"$TmpFile/Connect"
		;;
	'-showme')
		echo "4" >"$TmpFile/Connect"
		;;
	'-message')
		echo "$2" >"$TmpFile/LastMessage"
		echo "5" >"$TmpFile/Connect"
		[[ $3 == "-title" ]] && echo "$4" >"$TmpFile/MessageTitle"
		;;
	*)
		echo "Invalid argument $1"
		echo -e "$Usage" >&2
		exit 64
		;;
esac
